import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PrelineScript from "@/components/PrelineScript";
import Providers from "./providers";
import Navbar from "@/components/navbar";
import Layout from "@/components/Layout";
import Footer from "@/components/footer";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <PrelineScript />
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <Layout>
            {children}
          </Layout>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
